# local, dev, prod 공통 설정
application:
  version: 1.0.0
  title: backend_efub_twitter

server:
  port: 8080

spring:
  profiles:
    active: local # 적용할 프로필 선택

  devtools:
    livereload:
      enabled: true # spring-boot-devtools: live-reload

  main:
    allow-bean-definition-overriding: true # bean overriding 활성화

---
# =========================
# local 환경
# =========================
spring:
  config:
    activate:
      on-profile: local

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url:
    #username:
    #password:
    #url: jdbc:h2:mem:testdb # Set the database URL a constant

  h2:
    console:
      enabled: true # Enable H2 console
      settings:
        web-allow-others: true # Allow H2 console access from browser
    path: /h2-console

  jpa:
    show-sql: true # Show SQL generated

  sql:
    init:
      platform: mysql

  # Spring Security
  security:
    basic:
      enabled: false
    # Default username and password
    #user:
    #  name: username
    #  password: password

logging:
  level:
    root: info # debug

server:
  error:
    include-exception: true
    include-binding-errors: always
    whitelabel:
      enabled: true

---
# =========================
# dev 환경
# =========================
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://efub-twitter.cln9ditke2lj.ap-northeast-2.rds.amazonaws.com:3306/efubtwitter
    username: admin
    password: ewhaefubtwitter
      #url: jdbc:h2:mem:testdb # Set the database URL a constant

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true # Show SQL generated

  sql:
    init:
      platform: mysql

logging:
  level:
    root: info

---
# =========================
# prod 환경
# =========================
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://efub-twitter.cln9ditke2lj.ap-northeast-2.rds.amazonaws.com:3306/efubtwitter
    username: admin
    password: ewhaefubtwitter
      #url: jdbc:h2:mem:testdb # Set the database URL a constant

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  sql:
    init:
      platform: mysql

logging:
  level:
    root: error
